"""
Report Generator
================
Produces a standalone HTML data-quality report.
Optionally converts to PDF via weasyprint (if installed).
"""

import base64
import datetime
import json
import logging
import os
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Data Quality Report</title>
<style>
  :root {{
    --bg: #0f172a; --surface: #1e293b; --border: #334155;
    --accent: #6366f1; --accent2: #22d3ee;
    --text: #e2e8f0; --muted: #94a3b8;
    --ok: #22c55e; --warn: #f59e0b; --bad: #ef4444;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text);
          font-family: 'Segoe UI', system-ui, sans-serif; padding: 2rem; }}
  h1 {{ font-size: 2rem; background: linear-gradient(90deg, var(--accent), var(--accent2));
        -webkit-background-clip: text; -webkit-text-fill-color: transparent;
        margin-bottom: 0.25rem; }}
  .meta {{ color: var(--muted); font-size: 0.85rem; margin-bottom: 2rem; }}
  .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
            gap: 1rem; margin-bottom: 2rem; }}
  .card {{ background: var(--surface); border: 1px solid var(--border);
           border-radius: 12px; padding: 1.25rem; text-align: center; }}
  .card .val {{ font-size: 2rem; font-weight: 700; color: var(--accent2); }}
  .card .lbl {{ font-size: 0.75rem; color: var(--muted); margin-top: 0.25rem; }}
  section {{ margin-bottom: 2.5rem; }}
  h2 {{ font-size: 1.2rem; color: var(--accent2); border-bottom: 1px solid var(--border);
        padding-bottom: 0.5rem; margin-bottom: 1rem; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; }}
  th {{ background: var(--surface); color: var(--muted); text-align: left;
        padding: 0.6rem 0.8rem; border-bottom: 1px solid var(--border); }}
  td {{ padding: 0.55rem 0.8rem; border-bottom: 1px solid var(--border); vertical-align: top; }}
  tr:hover td {{ background: rgba(99,102,241,0.06); }}
  .badge {{ display: inline-block; padding: 0.2rem 0.55rem; border-radius: 99px;
            font-size: 0.72rem; font-weight: 600; }}
  .ok   {{ background: rgba(34,197,94,.15);  color: var(--ok); }}
  .warn {{ background: rgba(245,158,11,.15); color: var(--warn); }}
  .bad  {{ background: rgba(239,68,68,.15);  color: var(--bad); }}
  ul.tips {{ list-style: none; }}
  ul.tips li {{ background: var(--surface); border-left: 3px solid var(--accent);
                padding: 0.65rem 1rem; margin-bottom: 0.5rem; border-radius: 0 8px 8px 0; }}
  .img-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(340px,1fr));
               gap: 1rem; }}
  .img-grid img {{ width: 100%; border-radius: 8px; border: 1px solid var(--border); }}
  footer {{ color: var(--muted); font-size: 0.75rem; text-align: center; margin-top: 3rem; }}
</style>
</head>
<body>
<h1>📊 Data Quality Report</h1>
<p class="meta">Generated: {generated_at}</p>

<div class="cards">
  <div class="card"><div class="val">{total_rows:,}</div><div class="lbl">Rows</div></div>
  <div class="card"><div class="val">{total_cols}</div><div class="lbl">Columns</div></div>
  <div class="card"><div class="val">{total_missing:,}</div><div class="lbl">Missing Values</div></div>
  <div class="card"><div class="val">{duplicate_rows:,}</div><div class="lbl">Duplicate Rows</div></div>
</div>

<section>
  <h2>Column Summary</h2>
  <table>
    <tr>
      <th>Column</th><th>Type</th><th>Nulls</th><th>Null %</th>
      <th>Unique</th><th>IQR Outliers</th><th>Z Outliers</th><th>Type Issue</th>
    </tr>
    {col_rows}
  </table>
</section>

<section>
  <h2>🤖 Cleaning Suggestions</h2>
  <ul class="tips">
    {tip_items}
  </ul>
</section>

{chart_section}

<footer>Auto-generated by DataCleaner Pro · Python data cleaning toolkit by kihagama ismael</footer>
</body>
</html>"""


def _badge(val, warn_thresh=1, bad_thresh=10):
    if val == 0:
        return f'<span class="badge ok">0</span>'
    elif val < bad_thresh:
        return f'<span class="badge warn">{val:,}</span>'
    else:
        return f'<span class="badge bad">{val:,}</span>'


def _img_to_b64(path: str) -> str:
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode()


def generate_html_report(
    report: dict,
    suggestions: list,
    chart_paths: Optional[list] = None,
    output_path: str = "report.html",
) -> str:
    """
    Generate a standalone HTML report.

    Parameters
    ----------
    report       : dict from cleaner.build_quality_report()
    suggestions  : list[str] from cleaner.suggest_cleaning_strategies()
    chart_paths  : optional list of image file paths to embed
    output_path  : where to write the HTML file
    """
    # Column rows
    col_rows_html = ""
    for c in report["columns"]:
        null_badge = _badge(c["null_count"], warn_thresh=1, bad_thresh=10)
        out_badge  = _badge(c["outliers_iqr"], warn_thresh=1, bad_thresh=5)
        outz_badge = _badge(c["outliers_z"],   warn_thresh=1, bad_thresh=5)
        type_html  = (f'<span class="badge warn">{c["type_issue"]}</span>'
                      if c["type_issue"] else '<span class="badge ok">ok</span>')
        null_pct   = f'{c["null_pct"]:.1f}%'
        col_rows_html += (
            f"<tr><td>{c['column']}</td><td>{c['dtype']}</td>"
            f"<td>{null_badge}</td><td>{null_pct}</td>"
            f"<td>{c['unique_values']:,}</td>"
            f"<td>{out_badge}</td><td>{outz_badge}</td>"
            f"<td>{type_html}</td></tr>\n"
        )

    # Tip items
    tip_items = "\n".join(f"<li>{tip}</li>" for tip in suggestions)

    # Charts
    chart_section = ""
    if chart_paths:
        imgs = []
        for path in chart_paths:
            if os.path.exists(path):
                b64 = _img_to_b64(path)
                imgs.append(f'<img src="data:image/png;base64,{b64}" alt="chart">')
        if imgs:
            chart_section = (
                "<section><h2>📈 Visualizations</h2>"
                '<div class="img-grid">' + "".join(imgs) + "</div></section>"
            )

    html = HTML_TEMPLATE.format(
        generated_at=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        total_rows=report["total_rows"],
        total_cols=report["total_cols"],
        total_missing=report["total_missing"],
        duplicate_rows=report["duplicate_rows"],
        col_rows=col_rows_html,
        tip_items=tip_items,
        chart_section=chart_section,
    )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    logger.info(f"HTML report saved to {output_path}")
    return output_path


def generate_pdf_report(html_path: str, pdf_path: str) -> Optional[str]:
    """
    Convert HTML report to PDF using WeasyPrint.
    Returns path on success, None if WeasyPrint is unavailable.
    """
    try:
        from weasyprint import HTML
        HTML(filename=html_path).write_pdf(pdf_path)
        logger.info(f"PDF report saved to {pdf_path}")
        return pdf_path
    except ImportError:
        logger.warning("WeasyPrint not installed — PDF export skipped.")
        return None
    except Exception as e:
        logger.error(f"PDF export failed: {e}")
        return None
